---

availability_zone: melbourne-qh2-uom

#volume
volumes:
  - volume_name: volomn1
    vol_size: 50
  - volume_name: volomn2
    vol_size: 50
  - volume_name: volomn3
    vol_size: 50
  - volume_name: volomn4
    vol_size: 50


#Security groups
security_groups:
  - name: ssh_rule
    description: "for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http_rule
    description: "for http access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: db_5984
    description: "for couchdb access"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0


security_groups_lists: [ssh_rule, http_rule, db_5984, internal]

#Instances
instance_names: [couchdb1, couchdb2, couchdb3, web]
instance_image: 41a92d84-b2d4-4529-b729-1fb92153f0f0
instance_key: yycz
instance_flavor: uom.mse.2c9g
