---

- name: Docker - Apt Update
  apt:
    update_cache: yes
    upgrade: dist

- name: Docker - Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker - Set up the stable repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present
    filename: docker

- name: Docker - Install the latest version of Docker CE and containerd
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: latest

- name: Docker - Start Docker
  systemd:
    state: started
    name: docker

- name: Docker - Create proxy config file
  file:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    state: touch
    mode: 0766

- name: Docker - Setup proxy
  lineinfile:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    line: "{{ item }}"
  with_items:
    - '[Service]'
    - 'Environment="http_proxy=http://wwwproxy.unimelb.edu.au:8000" "https_proxy=http://wwwproxy.unimelb.edu.au:8000" "ftp_proxy=http://wwwproxy.unimelb.edu.au:8000" "no_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu"'

- name: Docker - Construct config directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0766

- name: Docker - Restart docker
  systemd:
    daemon_reload: yes
    state: restarted
    name: docker