---
- name: CouchDB - Docker container creating
  command: docker run -d --name couchdb --network host -p 5984:5984 -v /mnt/data:/opt/couchdb/data -e "COUCHDB_USER={{username}}" -e "COUCHDB_PASSWORD={{password}}" couchdb:2.3.0

- name: CouchDB - ammend for docker vm.args 
  command: "{{item}}"
  with_items:
    - docker exec couchdb bash -c "echo \"-setcookie cccGrp40\" >> /opt/couchdb/etc/vm.args"
    - docker exec couchdb bash -c "echo \"-name couchdb@{{ansible_default_ipv4.address}}\" >> /opt/couchdb/etc/vm.args"

- name: CouchDB - restart couchdb
  command: docker restart couchdb

- name: CouchDB - pause 15 seconds to wait for couchdb restart
  pause:
    seconds: 15

- name: CouchDB - config bind_address and UUID
  command: "{{item}}"
  with_items:
    - curl -X PUT http://{{username}}:{{password}}@127.0.0.1:5984/_node/_local/_config/chttpd/bind_address -d '"0.0.0.0"'
    - curl -X PUT http://{{username}}:{{password}}@127.0.0.1:5984/_node/_local/_config/httpd/bind_address -d '"0.0.0.0"'
    - curl -X PUT http://{{username}}:{{password}}@127.0.0.1:5984/_node/_local/_config/couchdb/uuid -d '"184ce9c08d17f4182c52fc8fa4000e13"'
    - curl -X PUT http://{{username}}:{{password}}@127.0.0.1:5984/_node/_local/_config/couch_httpd_auth/secret -d '"184ce9c08d17f4182c52fc8fa4000f2d"'



