- name: Install pip3
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes

- name: Update pip3
  pip:
    name: ['pip']
    state: latest
    executable: pip3

- name: Install couchdb package
  pip:
    name: ['couchdb']
    state: latest