---
- name: Create security group rules
  os_security_group_rule:
    security_group: '{{ item.name }}'
    port_range_max: '{{ item.port_range_max }}'
    port_range_min: '{{ item.port_range_min }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    protocol: '{{ item.protocol }}'
    state: present
  with_items: '{{ security_groups }}'

- name: Create security groups (SSH, HTTP, couchDB)
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  with_items: '{{ security_groups }}'

- name: Create security group rules for internal
  os_security_group_rule:
    security_group: internal
    remote_group: internal
    protocol: "{{ item }}"
    state: present
  with_items:
    - tcp
    - udp
    - icmp

- name: Create internal security group
  os_security_group:
    name: internal
    description: internal connection with remote_group as itself
    state: present