---

- hosts: webserver
  become: yes
  roles:
    - setup_tomcat


- hosts: webserver
  become: yes
  tasks:
    - name: upload web files
      copy:
        src: website/
        dest: /opt/tomcat/apache-tomcat-9.0.35/webapps/ROOT/
        mode: 0755
        owner: ubuntu
        group: ubuntu
    - name: start tomcat
      systemd:
        state: started
        daemon_reload: yes
        name: tomcat

