- name: Format Volume
  filesystem:
    fstype: ext4
    dev: /dev/vdb

- name: Create Mount Dir
  file:
    path: /mnt/data
    state: directory

- name: Mount Volume
  mount:
    path: /mnt/data
    src: /dev/vdb
    fstype: ext4
    state: mounted

- name: Change the Permission of directory '/mnt/data'
  file:
    path: /mnt/data
    mode: 0777
    recurse: yes
    state: directory
