---

- name: Setup cluster - Step 1
  command: "curl -X POST -H \"Content-Type: application/json\" http://{{username}}:{{password}}@{{ansible_default_ipv4.address}}:5984/_cluster_setup -d '{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\", \"username\": \"{{username}}\", \"password\": \"{{password}}\", \"port\": 5984, \"node_count\": \"3\", \"remote_node\": \"{{item}}\", \"remote_current_user\": \"{{username}}\", \"remote_current_password\": \"{{password}}\" }'"
  with_items: "{{groups['db_slave']}}"

- name: Setup cluster - Step 2
  command: "curl -X POST -H \"Content-Type: application/json\" http://{{username}}:{{password}}@{{ansible_default_ipv4.address}}:5984/_cluster_setup -d '{\"action\": \"add_node\", \"host\":\"{{item}}\", \"port\": 5984, \"username\": \"{{username}}\", \"password\": \"{{password}}\"}'"
  with_items: "{{groups['db_slave']}}"

- name: Setup cluster - Step 3
  command: "curl -X POST -H \"Content-Type: application/json\" http://{{username}}:{{password}}@{{ansible_default_ipv4.address}}:5984/_cluster_setup -d '{\"action\": \"finish_cluster\"}'"
  with_items: "{{groups['db_slave']}}"

- name: Setup cluster - remove nonode@nohost
  shell: "{{item}}" 
  with_items:
    - rev=`curl -XGET "http://{{ansible_default_ipv4.address}}:5986/_nodes/nonode@nohost" --user "{{username}}:{{password}}" | sed -e 's/[{}"]//g' | cut -f3 -d:`
    - curl -X DELETE "http://{{ansible_default_ipv4.address}}:5986/_nodes/nonode@nohost?rev=${rev}"  --user "{{username}}:{{password}}"

- name: Setup cluster - create database
  command: curl -X PUT "http://{{ansible_default_ipv4.address}}:5984/{{item}}?n=3&q=8" --user "{{username}}:{{password}}"
  with_items:  
    - grp40_tweet_harvester
    - grp40_aurin_data

  
